EncuestasWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EncuestasWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Encuestas UPC";

            return View();
        }
        public ActionResult Analista()
        {
            return View();
        }

        public ActionResult Administrador()
        {
            return View();
        }

        public ActionResult Docente()
        {
            return View();
        }

        public ActionResult Alumno()
        {
            return View();
        }

        public ActionResult Administrativo()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

EncuestasWeb/Controllers/TiposController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EncuestasWeb.Models;

namespace EncuestasWeb.Controllers
{
    public class TiposController : Controller
    {
        private EncuestasUPCEntities db = new EncuestasUPCEntities();

        // GET: Tipos
        public ActionResult Index()
        {
            var tipos = db.Tipos.Include(t => t.Categoria);
            return View(tipos.ToList());
        }

        // GET: Tipos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tipos tipos = db.Tipos.Find(id);
            if (tipos == null)
            {
                return HttpNotFound();
            }
            return View(tipos);
        }

        // GET: Tipos/Create
        public ActionResult Create()
        {
            ViewBag.CategoriaId = new SelectList(db.Categorias, "id", "NombreCategoria");
            return View();
        }

        // POST: Tipos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,NombreTipo,CategoriaId")] Tipos tipos)
        {
            if (ModelState.IsValid)
            {
                db.Tipos.Add(tipos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoriaId = new SelectList(db.Categorias, "id", "NombreCategoria", tipos.CategoriaId);
            return View(tipos);
        }

        // GET: Tipos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tipos tipos = db.Tipos.Find(id);
            if (tipos == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoriaId = new SelectList(db.Categorias, "id", "NombreCategoria", tipos.CategoriaId);
            return View(tipos);
        }

        // POST: Tipos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,NombreTipo,CategoriaId")] Tipos tipos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoriaId = new SelectList(db.Categorias, "id", "NombreCategoria", tipos.CategoriaId);
            return View(tipos);
        }

        // GET: Tipos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tipos tipos = db.Tipos.Find(id);
            if (tipos == null)
            {
                return HttpNotFound();
            }
            return View(tipos);
        }

        // POST: Tipos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tipos tipos = db.Tipos.Find(id);
            db.Tipos.Remove(tipos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EncuestasWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Encuestas UPC fue desarrollada por: </p>
<p>Hugo Bullon</p>
<p>Renzo Marines</p>
<p>Franyo Vilcamiche</p>

EncuestasWeb/Views/Home/Administrador.cshtml
@{
    ViewBag.Title = "Administrador";
}

<h2>Panel de Administrador</h2>

<p>
    @Html.ActionLink("Administrar Indicadores", "Index", "Indicadores")
</p>
<p>
    @Html.ActionLink("Administrar Categorías", "Index", "Categorias")
</p>

<p>
    @Html.ActionLink("Administrar Tipos", "Index", "Tipos")
</p>

<p>
    @Html.ActionLink("Administrar SubTipos", "Index", "Subtipoes")
</p>

<p>
    @Html.ActionLink("Administrar Encuestas", "Index", "Encuestas")
</p>

<p>
    @Html.ActionLink("Administrar Documentos Digitales", "Index", "DocumentosDigitales")
</p>

<p>
    @Html.ActionLink("Administrar Usuarios", "Index", "Usuarios")
</p>

<p>
    @Html.ActionLink("Administrar Grupos", "Index", "Grupos")
</p>

<p>
    @Html.ActionLink("Administrar Preguntas", "Index", "Preguntas")
</p>

<p>
    @Html.ActionLink("Administrar Opciones", "Index", "Opciones")
</p>

EncuestasWeb/Views/Home/Analista.cshtml
@{
    ViewBag.Title = "Analista";
}

<h2>Panel de Analista</h2>

<p>
    @Html.ActionLink("Administrar Indicadores", "Index", "Indicadores")
</p>
<p>
    @Html.ActionLink("Administrar Categorías", "Index", "Categorias")
</p>

<p>
    @Html.ActionLink("Administrar Tipos", "Index", "Tipos")
</p>

<p>
    @Html.ActionLink("Administrar SubTipos", "Index", "Subtipoes")
</p>

<p>
    @Html.ActionLink("Crear Encuesta", "Create", "Encuestas")
</p>

<p>
    @Html.ActionLink("Administrar Documentos Digitales", "Index", "DocumentosDigitales")
</p>

EncuestasWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EncuestasWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Encuestas UPC";
}

<div class="jumbotron">
    <h1>Encuestas UPC</h1>
    <p class="lead">Encuestas UPC es el nuevo sistema de encuestas para la Universidad Peruana de Ciencias Aplicadas.</p>
    <p><a href="/Usuarios/Login" class="btn btn-danger btn-lg">Iniciar Sesión &raquo;</a></p>
</div>

<div class="row">
</div>